### ISSUE TITLE
Use a Tailwind UI navbar

### ISSUE THREAD

**Issue by cwbieganek** [cwbieganek/sales-dashboard#9]
- [ ] Create a navbar component
- [ ] Component includes logo
- [ ] Component includes a title prop
- [ ] Component added to +layout.svelte

**Comment by Advaith-RN** [comment]
Mind if I work on this?

**Comment by cwbieganek** [comment]
> Mind if I work on this?

Hi there! This is just a simple project for my portfolio. I am planning on doing all the work. Thank you for your interest though!
